{
    "status": "Fix Released", 
    "last_updated": "2013-04-04 11:20:19.792098+00:00", 
    "description": "From latest devstack on 2013-3-4\n\nbox:~/devstack$ sudo nova-manage db archive_deleted_rows --max_rows -5\n\n\nCommand failed, please check log for more info\n\n2013-03-05 00:49:41.631 CRITICAL nova [req-ee44b54f-27b5-473b-8349-4ab42f95d725 None None] (ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-5' at line 4\") 'SELECT aggregate_metadata.created_at, aggregate_metadata.updated_at, aggregate_metadata.deleted_at, aggregate_metadata.id, aggregate_metadata.aggregate_id, aggregate_metadata.`key`, aggregate_metadata.value, aggregate_metadata.deleted \\nFROM aggregate_metadata \\nWHERE aggregate_metadata.deleted != %s ORDER BY aggregate_metadata.id \\n LIMIT %s' (0, -5)\n2013-03-05 00:49:41.631 8904 TRACE nova Traceback (most recent call last):\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/usr/local/bin/nova-manage\", line 7, in <module>\n2013-03-05 00:49:41.631 8904 TRACE nova     execfile(__file__)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/opt/stack/nova/bin/nova-manage\", line 1247, in <module>\n2013-03-05 00:49:41.631 8904 TRACE nova     main()\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/opt/stack/nova/bin/nova-manage\", line 1239, in main\n2013-03-05 00:49:41.631 8904 TRACE nova     fn(*fn_args, **fn_kwargs)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/opt/stack/nova/bin/nova-manage\", line 800, in archive_deleted_rows\n2013-03-05 00:49:41.631 8904 TRACE nova     db.archive_deleted_rows(admin_context, max_rows)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/opt/stack/nova/nova/db/api.py\", line 1705, in archive_deleted_rows2013-03-05 00:49:41.631 8904 TRACE nova     return IMPL.archive_deleted_rows(context, max_rows=max_rows)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/opt/stack/nova/nova/db/sqlalchemy/api.py\", line 95, in wrapper\n2013-03-05 00:49:41.631 8904 TRACE nova     return f(*args, **kwargs)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/opt/stack/nova/nova/db/sqlalchemy/api.py\", line 4779, in archive_deleted_rows\n2013-03-05 00:49:41.631 8904 TRACE nova     max_rows=max_rows - rows_archived)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/opt/stack/nova/nova/db/sqlalchemy/api.py\", line 95, in wrapper2013-03-05 00:49:41.631 8904 TRACE nova     return f(*args, **kwargs)2013-03-05 00:49:41.631 8904 TRACE nova   File \"/opt/stack/nova/nova/db/sqlalchemy/api.py\", line 4751, in archive_deleted_rows_for_table\n2013-03-05 00:49:41.631 8904 TRACE nova     rows = conn.execute(query).fetchall()\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py\", line 1449, in execute\n2013-03-05 00:49:41.631 8904 TRACE nova     params)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py\", line 1584, in _execute_clauseelement\n2013-03-05 00:49:41.631 8904 TRACE nova     compiled_sql, distilled_params\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py\", line 1698, in _execute_context\n2013-03-05 00:49:41.631 8904 TRACE nova     context)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py\", line 1691, in _execute_context\n2013-03-05 00:49:41.631 8904 TRACE nova     context)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py\", line 331, in do_execute\n2013-03-05 00:49:41.631 8904 TRACE nova     cursor.execute(statement, parameters)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py\", line 174, in execute\n2013-03-05 00:49:41.631 8904 TRACE nova     self.errorhandler(self, exc, value)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/usr/lib/python2.7/dist-packages/MySQLdb/connections.py\", line 36, in defaulterrorhandler\n2013-03-05 00:49:41.631 8904 TRACE nova     raise errorclass, errorvalue\n2013-03-05 00:49:41.631 8904 TRACE nova ProgrammingError: (ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-5' at line 4\") 'SELECT aggregate_metadata.created_at, aggregate_metadata.updated_at, aggregate_metadata.deleted_at, aggregate_metadata.id, aggregate_metadata.aggregate_id, aggregate_metadata.`key`, aggregate_metadata.value, aggregate_metadata.deleted \\nFROM aggregate_metadata \\nWHERE aggregate_metadata.deleted != %s ORDER BY aggregate_metadata.id \\n LIMIT %s' (0, -5)", 
    "tags": [], 
    "importance": "Undecided", 
    "heat": 6, 
    "link": "https://bugs.launchpad.net/nova/+bug/1145609", 
    "owner": "https://api.launchpad.net/1.0/~jogo", 
    "id": 1145609, 
    "index": 3470, 
    "created": "2013-03-05 00:51:40.505000+00:00", 
    "title": "nova-manage db archive_deleted_rows  doesn't check for negative max_rows", 
    "comments": [
        {
            "content": "From latest devstack on 2013-3-4\n\nbox:~/devstack$ sudo nova-manage db archive_deleted_rows --max_rows -5\n\n\nCommand failed, please check log for more info\n\n2013-03-05 00:49:41.631 CRITICAL nova [req-ee44b54f-27b5-473b-8349-4ab42f95d725 None None] (ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-5' at line 4\") 'SELECT aggregate_metadata.created_at, aggregate_metadata.updated_at, aggregate_metadata.deleted_at, aggregate_metadata.id, aggregate_metadata.aggregate_id, aggregate_metadata.`key`, aggregate_metadata.value, aggregate_metadata.deleted \\nFROM aggregate_metadata \\nWHERE aggregate_metadata.deleted != %s ORDER BY aggregate_metadata.id \\n LIMIT %s' (0, -5)\n2013-03-05 00:49:41.631 8904 TRACE nova Traceback (most recent call last):\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/usr/local/bin/nova-manage\", line 7, in <module>\n2013-03-05 00:49:41.631 8904 TRACE nova     execfile(__file__)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/opt/stack/nova/bin/nova-manage\", line 1247, in <module>\n2013-03-05 00:49:41.631 8904 TRACE nova     main()\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/opt/stack/nova/bin/nova-manage\", line 1239, in main\n2013-03-05 00:49:41.631 8904 TRACE nova     fn(*fn_args, **fn_kwargs)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/opt/stack/nova/bin/nova-manage\", line 800, in archive_deleted_rows\n2013-03-05 00:49:41.631 8904 TRACE nova     db.archive_deleted_rows(admin_context, max_rows)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/opt/stack/nova/nova/db/api.py\", line 1705, in archive_deleted_rows2013-03-05 00:49:41.631 8904 TRACE nova     return IMPL.archive_deleted_rows(context, max_rows=max_rows)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/opt/stack/nova/nova/db/sqlalchemy/api.py\", line 95, in wrapper\n2013-03-05 00:49:41.631 8904 TRACE nova     return f(*args, **kwargs)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/opt/stack/nova/nova/db/sqlalchemy/api.py\", line 4779, in archive_deleted_rows\n2013-03-05 00:49:41.631 8904 TRACE nova     max_rows=max_rows - rows_archived)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/opt/stack/nova/nova/db/sqlalchemy/api.py\", line 95, in wrapper2013-03-05 00:49:41.631 8904 TRACE nova     return f(*args, **kwargs)2013-03-05 00:49:41.631 8904 TRACE nova   File \"/opt/stack/nova/nova/db/sqlalchemy/api.py\", line 4751, in archive_deleted_rows_for_table\n2013-03-05 00:49:41.631 8904 TRACE nova     rows = conn.execute(query).fetchall()\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py\", line 1449, in execute\n2013-03-05 00:49:41.631 8904 TRACE nova     params)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py\", line 1584, in _execute_clauseelement\n2013-03-05 00:49:41.631 8904 TRACE nova     compiled_sql, distilled_params\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py\", line 1698, in _execute_context\n2013-03-05 00:49:41.631 8904 TRACE nova     context)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py\", line 1691, in _execute_context\n2013-03-05 00:49:41.631 8904 TRACE nova     context)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py\", line 331, in do_execute\n2013-03-05 00:49:41.631 8904 TRACE nova     cursor.execute(statement, parameters)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py\", line 174, in execute\n2013-03-05 00:49:41.631 8904 TRACE nova     self.errorhandler(self, exc, value)\n2013-03-05 00:49:41.631 8904 TRACE nova   File \"/usr/lib/python2.7/dist-packages/MySQLdb/connections.py\", line 36, in defaulterrorhandler\n2013-03-05 00:49:41.631 8904 TRACE nova     raise errorclass, errorvalue\n2013-03-05 00:49:41.631 8904 TRACE nova ProgrammingError: (ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-5' at line 4\") 'SELECT aggregate_metadata.created_at, aggregate_metadata.updated_at, aggregate_metadata.deleted_at, aggregate_metadata.id, aggregate_metadata.aggregate_id, aggregate_metadata.`key`, aggregate_metadata.value, aggregate_metadata.deleted \\nFROM aggregate_metadata \\nWHERE aggregate_metadata.deleted != %s ORDER BY aggregate_metadata.id \\n LIMIT %s' (0, -5)", 
            "date_created": "2013-03-05 00:51:40.505000+00:00", 
            "author": "https://api.launchpad.net/1.0/~jogo"
        }, 
        {
            "content": "Fix proposed to branch: master\nReview: https://review.openstack.org/23496", 
            "date_created": "2013-03-05 01:12:39.612130+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/23496\nCommitted: http://github.com/openstack/nova/commit/abc0c9479127671adf8fcd81197ab993356cbc6a\nSubmitter: Jenkins\nBranch:    master\n\ncommit abc0c9479127671adf8fcd81197ab993356cbc6a\nAuthor: Joe Gordon <email address hidden>\nDate:   Tue Mar 5 01:11:45 2013 +0000\n\n    Make nova-manage db archive_deleted_rows more explicit\n    \n    * max_rows must be positive\n        Provide a better error message of 'nova-manage db archive_deleted_rows\n        --max_rows=' is negative.\n    * Requires a max_rows\n    * No hidden default of 5000\n    \n    Fix bug 1145609\n    Fix bug 1151064\n    \n    Change-Id: I9078ff2700a0329ac4aff68bb434be5f16a5a3f1\n", 
            "date_created": "2013-03-08 20:55:33.102528+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }
    ]
}