{
    "status": "Fix Released", 
    "last_updated": "2014-03-21 11:12:15.679815+00:00", 
    "description": "I believe this is because the following call was added to compute/api.py:\n\n@wrap_check_policy\ndef get_all_instance_metadata(self, context, search_filts):\n\nAnd check_policy needs a target (an instance) to check against -- all the other functions that use this wrapper have (self, context, instance) as the first three arguments.\n\nRemoving the wrapper lets the call succeed, but is it the right thing to do?\n\n--\n\n2013-06-19 21:04:38.221 16387 DEBUG nova.utils [-] Reloading cached file /etc/nova/policy.json read_cached_file /opt/stack/nova/nova/utils.py:750\n2013-06-19 21:04:38.250 DEBUG nova.api.ec2 [req-7848f2fe-0069-45c9-abe0-9fd10d45fee3 demo demo] action: DescribeTags __call__ /opt/stack/nova/nova/api/ec2/__init__.py:336\n2013-06-19 21:04:38.254 ERROR nova.api.ec2 [req-7848f2fe-0069-45c9-abe0-9fd10d45fee3 demo demo] Unexpected error raised: list indices must be integers, not unicode\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2 Traceback (most recent call last):\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/api/ec2/__init__.py\", line 486, in __call__\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     result = api_request.invoke(context)\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/api/ec2/apirequest.py\", line 79, in invoke\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     result = method(context, **args)\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/api/ec2/cloud.py\", line 1826, in describe_tags\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     search_filts):\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/compute/api.py\", line 169, in wrapped\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     check_policy(context, func.__name__, target, scope)\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/compute/api.py\", line 181, in check_policy\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     nova.policy.enforce(context, _action, target)\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/policy.py\", line 102, in enforce\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     return policy.check(action, target, credentials, **extra)\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/openstack/common/policy.py\", line 175, in check\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     result = _rules[rule](target, creds)\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/openstack/common/policy.py\", line 731, in __call__\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     return _rules[self.match](target, creds)\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/openstack/common/policy.py\", line 365, in __call__\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     if rule(target, cred):\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/openstack/common/policy.py\", line 776, in __call__\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     match = self.match % target\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2 TypeError: list indices must be integers, not unicode", 
    "tags": [
        "ec2"
    ], 
    "importance": "Undecided", 
    "heat": 8, 
    "link": "https://bugs.launchpad.net/nova/+bug/1192715", 
    "owner": "https://api.launchpad.net/1.0/~holzman", 
    "id": 1192715, 
    "index": 3768, 
    "created": "2013-06-19 21:14:53.588841+00:00", 
    "title": "nova ec2-api: euca-describe-tags fails with UnknownError", 
    "comments": [
        {
            "content": "I believe this is because the following call was added to compute/api.py:\n\n@wrap_check_policy\ndef get_all_instance_metadata(self, context, search_filts):\n\nAnd check_policy needs a target (an instance) to check against -- all the other functions that use this wrapper have (self, context, instance) as the first three arguments.\n\nRemoving the wrapper lets the call succeed, but is it the right thing to do?\n\n--\n\n2013-06-19 21:04:38.221 16387 DEBUG nova.utils [-] Reloading cached file /etc/nova/policy.json read_cached_file /opt/stack/nova/nova/utils.py:750\n2013-06-19 21:04:38.250 DEBUG nova.api.ec2 [req-7848f2fe-0069-45c9-abe0-9fd10d45fee3 demo demo] action: DescribeTags __call__ /opt/stack/nova/nova/api/ec2/__init__.py:336\n2013-06-19 21:04:38.254 ERROR nova.api.ec2 [req-7848f2fe-0069-45c9-abe0-9fd10d45fee3 demo demo] Unexpected error raised: list indices must be integers, not unicode\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2 Traceback (most recent call last):\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/api/ec2/__init__.py\", line 486, in __call__\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     result = api_request.invoke(context)\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/api/ec2/apirequest.py\", line 79, in invoke\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     result = method(context, **args)\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/api/ec2/cloud.py\", line 1826, in describe_tags\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     search_filts):\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/compute/api.py\", line 169, in wrapped\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     check_policy(context, func.__name__, target, scope)\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/compute/api.py\", line 181, in check_policy\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     nova.policy.enforce(context, _action, target)\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/policy.py\", line 102, in enforce\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     return policy.check(action, target, credentials, **extra)\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/openstack/common/policy.py\", line 175, in check\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     result = _rules[rule](target, creds)\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/openstack/common/policy.py\", line 731, in __call__\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     return _rules[self.match](target, creds)\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/openstack/common/policy.py\", line 365, in __call__\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     if rule(target, cred):\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2   File \"/opt/stack/nova/nova/openstack/common/policy.py\", line 776, in __call__\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2     match = self.match % target\n2013-06-19 21:04:38.254 16387 TRACE nova.api.ec2 TypeError: list indices must be integers, not unicode", 
            "date_created": "2013-06-19 21:14:53.588841+00:00", 
            "author": "https://api.launchpad.net/1.0/~holzman"
        }, 
        {
            "content": "Maybe sending in the context as an extra argument makes sense since it has the project_id.  I'll submit a patch.\n", 
            "date_created": "2013-06-19 21:41:29.397851+00:00", 
            "author": "https://api.launchpad.net/1.0/~holzman"
        }, 
        {
            "content": "On second thought, that doesn't make much sense, it would always evaluate to true.\n\nWe should probably fetch all the metadata and add a post-filtering step where we loop through the\ninstances and check the policy on each.\n", 
            "date_created": "2013-06-19 22:00:13.757987+00:00", 
            "author": "https://api.launchpad.net/1.0/~holzman"
        }, 
        {
            "content": "Fix proposed to branch: master\nReview: https://review.openstack.org/33782", 
            "date_created": "2013-06-20 07:37:10.979943+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Fix proposed to branch: master\nReview: https://review.openstack.org/36111", 
            "date_created": "2013-07-08 17:42:53.585038+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Fix proposed to branch: master\nReview: https://review.openstack.org/36241", 
            "date_created": "2013-07-09 15:37:46.039361+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Fix proposed to branch: master\nReview: https://review.openstack.org/36242", 
            "date_created": "2013-07-09 15:37:57.996223+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Fix proposed to branch: master\nReview: https://review.openstack.org/36243", 
            "date_created": "2013-07-09 15:38:07.988394+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Fix proposed to branch: master\nReview: https://review.openstack.org/36244", 
            "date_created": "2013-07-09 15:38:18.576608+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/36241\nCommitted: http://github.com/openstack/nova/commit/08559964bd209de823fd5e4738519514172d0b26\nSubmitter: Jenkins\nBranch:    master\n\ncommit 08559964bd209de823fd5e4738519514172d0b26\nAuthor: Burt Holzman <email address hidden>\nDate:   Tue Jul 9 09:03:12 2013 -0500\n\n    Replace get_instance_metadata call in api.ec2.cloud._format_instances\n    \n    The _format_instances method in api.ec2.cloud populates an instance\n    dictionary from the sqlalchemy instance model objects, and populates the\n    metadata by calling compute.api.get_instance_metadata.\n    \n    This is unnecessary, since the instance objects already have metadata\n    attached. The helper class is needed until the migration to nova objects\n    is complete.\n    \n    Partially fixes bug #1192715\n    \n    Change-Id: Ib5a593bd36c8d6a531b9494b9861cca9a40ed08a\n", 
            "date_created": "2013-07-17 06:23:40.244374+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/36243\nCommitted: http://github.com/openstack/nova/commit/c43bc58aa1e2dfaf3c6787560ec2d09af0a819ae\nSubmitter: Jenkins\nBranch:    master\n\ncommit c43bc58aa1e2dfaf3c6787560ec2d09af0a819ae\nAuthor: Burt Holzman <email address hidden>\nDate:   Tue Jul 9 09:49:37 2013 -0500\n\n    Sort output for unit tests in test_describe_tags before compare\n    \n    There's no guarantees on what order the output from describe_tags\n    comes back in, so it needs to be sorted.\n    \n    Partially fixes bug #1192715\n    \n    Change-Id: Ibb2619e8077ea8b8bd4796f9ffe89c2376d047f6\n", 
            "date_created": "2013-07-17 08:07:32.770697+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/36244\nCommitted: http://github.com/openstack/nova/commit/b48789f14b41b7f017f84a5d832e9283a0808ef4\nSubmitter: Jenkins\nBranch:    master\n\ncommit b48789f14b41b7f017f84a5d832e9283a0808ef4\nAuthor: Burt Holzman <email address hidden>\nDate:   Tue Jul 9 09:58:20 2013 -0500\n\n    Change get_all_instance_metadata to use _get_instances_by_filters\n    \n    We need an instance list for invoking check_policy against when calling\n    get_all_instance_metadata. Since the _get_instances_by_filters\n    call also returns associated instance metadata, we can use this instead\n    of db.api.get_all_instance_metadata.\n    \n    Fixes bug #1192715\n    \n    Change-Id: Idb005b7227447308a8d060be7aa9ff5c70b5ff44\n", 
            "date_created": "2013-07-17 09:01:21.175461+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }
    ]
}