{
    "status": "Fix Released", 
    "last_updated": "2015-04-30 09:10:50.617553+00:00", 
    "description": "nova service disable/enable returns 500 on cell environment. Actual enable/disable looks processed correctly.\n\nIt also throws following error in nova-api service:\nValueError: invalid literal for int() with base 10: 'region!child@5'\n\nHow to reproduce:\n\n$ nova --os-username admin service-list\n\nOutput:\n+----------------+------------------+---------------------+----------+---------+-------+----------------------------+-----------------+\n| Id             | Binary           | Host                | Zone     | Status  | State | Updated_at                 | Disabled Reason |\n+----------------+------------------+---------------------+----------+---------+-------+----------------------------+-----------------+\n| region!child@1 | nova-conductor   | region!child@ubuntu | internal | enabled | up    | 2014-08-18T06:17:36.000000 | -               |\n| region!child@3 | nova-cells       | region!child@ubuntu | internal | enabled | up    | 2014-08-18T06:17:29.000000 | -               |\n| region!child@4 | nova-scheduler   | region!child@ubuntu | internal | enabled | up    | 2014-08-18T06:17:30.000000 | -               |\n| region!child@5 | nova-compute     | region!child@ubuntu | nova     | enabled | up    | 2014-08-18T06:17:31.000000 | -               |\n| region@1       | nova-cells       | region@ubuntu       | internal | enabled | up    | 2014-08-18T06:17:29.000000 | -               |\n| region@2       | nova-cert        | region@ubuntu       | internal | enabled | down  | 2014-08-18T06:08:28.000000 | -               |\n| region@3       | nova-consoleauth | region@ubuntu       | internal | enabled | up    | 2014-08-18T06:17:37.000000 | -               |\n+----------------+------------------+---------------------+----------+---------+-------+----------------------------+-----------------+\n\n$ nova --os-username admin service-disable 'region!child@ubuntu' nova-compute\n\nThe above command gives the following error:\nERROR (ClientException): Unknown Error (HTTP 500)\n\n$ nova --os-username admin service-list\n\nOutput:\n+----------------+------------------+---------------------+----------+----------+-------+----------------------------+-----------------+\n| Id             | Binary           | Host                | Zone     | Status   | State | Updated_at                 | Disabled Reason |\n+----------------+------------------+---------------------+----------+----------+-------+----------------------------+-----------------+\n| region!child@1 | nova-conductor   | region!child@ubuntu | internal | enabled  | up    | 2014-08-18T06:19:06.000000 | -               |\n| region!child@3 | nova-cells       | region!child@ubuntu | internal | enabled  | up    | 2014-08-18T06:19:09.000000 | -               |\n| region!child@4 | nova-scheduler   | region!child@ubuntu | internal | enabled  | up    | 2014-08-18T06:19:10.000000 | -               |\n| region!child@5 | nova-compute     | region!child@ubuntu | nova     | disabled | up    | 2014-08-18T06:19:11.000000 | -               |\n| region@1       | nova-cells       | region@ubuntu       | internal | enabled  | up    | 2014-08-18T06:19:09.000000 | -               |\n| region@2       | nova-cert        | region@ubuntu       | internal | enabled  | down  | 2014-08-18T06:08:28.000000 | -               |\n| region@3       | nova-consoleauth | region@ubuntu       | internal | enabled  | up    | 2014-08-18T06:19:07.000000 | -               |\n+----------------+------------------+---------------------+----------+----------+-------+----------------------------+-----------------+\n\n$ nova --os-username admin service-enable 'region!child@ubuntu' nova-compute\nThe above command gives following error:\nERROR (ClientException): Unknown Error (HTTP 500)\n\n$ nova --os-username admin service-list\n+----------------+------------------+---------------------+----------+---------+-------+----------------------------+-----------------+\n| Id             | Binary           | Host                | Zone     | Status  | State | Updated_at                 | Disabled Reason |\n+----------------+------------------+---------------------+----------+---------+-------+----------------------------+-----------------+\n| region!child@1 | nova-conductor   | region!child@ubuntu | internal | enabled | up    | 2014-08-18T06:52:37.000000 | -               |\n| region!child@3 | nova-cells       | region!child@ubuntu | internal | enabled | up    | 2014-08-18T06:52:40.000000 | -               |\n| region!child@4 | nova-scheduler   | region!child@ubuntu | internal | enabled | up    | 2014-08-18T06:52:41.000000 | -               |\n| region!child@5 | nova-compute     | region!child@ubuntu | nova     | enabled | up    | 2014-08-18T06:52:42.000000 | -               |\n| region@1       | nova-cells       | region@ubuntu       | internal | enabled | up    | 2014-08-18T06:52:40.000000 | -               |\n| region@2       | nova-cert        | region@ubuntu       | internal | enabled | down  | 2014-08-18T06:08:28.000000 | -               |\n| region@3       | nova-consoleauth | region@ubuntu       | internal | enabled | up    | 2014-08-18T06:52:39.000000 | -               |\n+----------------+------------------+---------------------+----------+---------+-------+----------------------------+-----------------+\n\n\nThe nova-api log shows the following error, after we try to disable/enable the child cell service.\n\noutput of nova-api.log:\n\n2014-08-18 15:18:23.848 DEBUG nova.api.openstack.wsgi [req-c8e2b844-6aa4-4819-b4f4-38bfe30240f0 admin demo] Action: 'update', body: {\"binary\": \"nova-compute\", \"host\": \"region!child@ubuntu\"} from (pid=11556) _process_stack /opt/stack/nova/nova/api/openstack/wsgi.py:940\n2014-08-18 15:18:23.848 DEBUG nova.api.openstack.wsgi [req-c8e2b844-6aa4-4819-b4f4-38bfe30240f0 admin demo] Calling method '<bound method ServiceController.update of <nova.api.openstack.compute.contrib.services.ServiceController object at 0x7f16bd608510>>' (Content-type='application/json', Accept='application/json') from (pid=11556) _process_stack /opt/stack/nova/nova/api/openstack/wsgi.py:945\n2014-08-18 15:18:23.930 ERROR object [req-c8e2b844-6aa4-4819-b4f4-38bfe30240f0 admin demo] Error setting Service.id\n2014-08-18 15:18:23.930 TRACE object Traceback (most recent call last):\n2014-08-18 15:18:23.930 TRACE object   File \"/opt/stack/nova/nova/objects/base.py\", line 70, in setter\n2014-08-18 15:18:23.930 TRACE object     field.coerce(self, name, value))\n2014-08-18 15:18:23.930 TRACE object   File \"/opt/stack/nova/nova/objects/fields.py\", line 166, in coerce\n2014-08-18 15:18:23.930 TRACE object     return self._type.coerce(obj, attr, value)\n2014-08-18 15:18:23.930 TRACE object   File \"/opt/stack/nova/nova/objects/fields.py\", line 231, in coerce\n2014-08-18 15:18:23.930 TRACE object     return int(value)\n2014-08-18 15:18:23.930 TRACE object ValueError: invalid literal for int() with base 10: 'region!child@5'\n2014-08-18 15:18:23.930 TRACE object\n2014-08-18 15:18:23.934 ERROR nova.api.openstack [req-c8e2b844-6aa4-4819-b4f4-38bfe30240f0 admin demo] Caught error: invalid literal for int() with base 10: 'region!child@5'\n2014-08-18 15:18:23.934 TRACE nova.api.openstack Traceback (most recent call last):\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/api/openstack/__init__.py\", line 125, in __call__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return req.get_response(self.application)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/usr/lib/python2.7/dist-packages/webob/request.py\", line 1320, in send\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     application, catch_exc_info=False)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/usr/lib/python2.7/dist-packages/webob/request.py\", line 1284, in call_application\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     app_iter = application(self.environ, start_response)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 144, in __call__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return resp(environ, start_response)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/python-keystoneclient/keystoneclient/middleware/auth_token.py\", line 663, in __call__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return self.app(env, start_response)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 144, in __call__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return resp(environ, start_response)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 144, in __call__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return resp(environ, start_response)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/usr/local/lib/python2.7/dist-packages/routes/middleware.py\", line 131, in __call__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     response = self.app(environ, start_response)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 144, in __call__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return resp(environ, start_response)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 130, in __call__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     resp = self.call_func(req, *args, **self.kwargs)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 195, in call_func\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return self.func(req, *args, **kwargs)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/api/openstack/wsgi.py\", line 917, in __call__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     content_type, body, accept)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/api/openstack/wsgi.py\", line 983, in _process_stack\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     action_result = self.dispatch(meth, request, action_args)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/api/openstack/wsgi.py\", line 1070, in dispatch\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return method(req=request, **action_args)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/api/openstack/compute/contrib/services.py\", line 206, in update\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     self.host_api.service_update(context, host, binary, status_detail)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/compute/cells_api.py\", line 579, in service_update\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     db_service)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/objects/service.py\", line 67, in _from_db_object\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     service[key] = db_service[key]\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/objects/base.py\", line 398, in __setitem__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     setattr(self, name, value)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/objects/base.py\", line 70, in setter\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     field.coerce(self, name, value))\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/objects/fields.py\", line 166, in coerce\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return self._type.coerce(obj, attr, value)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/objects/fields.py\", line 231, in coerce\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return int(value)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack ValueError: invalid literal for int() with base 10: 'region!child@5'", 
    "tags": [
        "cells", 
        "ntt"
    ], 
    "importance": "High", 
    "heat": 34, 
    "link": "https://bugs.launchpad.net/nova/+bug/1361180", 
    "owner": "https://api.launchpad.net/1.0/~dheeraj-gupta4", 
    "id": 1361180, 
    "index": 1582, 
    "created": "2014-08-25 12:19:36.025388+00:00", 
    "title": "nova service disable/enable returns 500 on cell environment", 
    "comments": [
        {
            "content": "nova service disable/enable returns 500 on cell environment. Actual enable/disable looks processed correctly.\n\nIt also throws following error in nova-api service:\nValueError: invalid literal for int() with base 10: 'region!child@5'\n\nHow to reproduce:\n\n$ nova --os-username admin service-list\n\nOutput:\n+----------------+------------------+---------------------+----------+---------+-------+----------------------------+-----------------+\n| Id             | Binary           | Host                | Zone     | Status  | State | Updated_at                 | Disabled Reason |\n+----------------+------------------+---------------------+----------+---------+-------+----------------------------+-----------------+\n| region!child@1 | nova-conductor   | region!child@ubuntu | internal | enabled | up    | 2014-08-18T06:17:36.000000 | -               |\n| region!child@3 | nova-cells       | region!child@ubuntu | internal | enabled | up    | 2014-08-18T06:17:29.000000 | -               |\n| region!child@4 | nova-scheduler   | region!child@ubuntu | internal | enabled | up    | 2014-08-18T06:17:30.000000 | -               |\n| region!child@5 | nova-compute     | region!child@ubuntu | nova     | enabled | up    | 2014-08-18T06:17:31.000000 | -               |\n| region@1       | nova-cells       | region@ubuntu       | internal | enabled | up    | 2014-08-18T06:17:29.000000 | -               |\n| region@2       | nova-cert        | region@ubuntu       | internal | enabled | down  | 2014-08-18T06:08:28.000000 | -               |\n| region@3       | nova-consoleauth | region@ubuntu       | internal | enabled | up    | 2014-08-18T06:17:37.000000 | -               |\n+----------------+------------------+---------------------+----------+---------+-------+----------------------------+-----------------+\n\n$ nova --os-username admin service-disable 'region!child@ubuntu' nova-compute\n\nThe above command gives the following error:\nERROR (ClientException): Unknown Error (HTTP 500)\n\n$ nova --os-username admin service-list\n\nOutput:\n+----------------+------------------+---------------------+----------+----------+-------+----------------------------+-----------------+\n| Id             | Binary           | Host                | Zone     | Status   | State | Updated_at                 | Disabled Reason |\n+----------------+------------------+---------------------+----------+----------+-------+----------------------------+-----------------+\n| region!child@1 | nova-conductor   | region!child@ubuntu | internal | enabled  | up    | 2014-08-18T06:19:06.000000 | -               |\n| region!child@3 | nova-cells       | region!child@ubuntu | internal | enabled  | up    | 2014-08-18T06:19:09.000000 | -               |\n| region!child@4 | nova-scheduler   | region!child@ubuntu | internal | enabled  | up    | 2014-08-18T06:19:10.000000 | -               |\n| region!child@5 | nova-compute     | region!child@ubuntu | nova     | disabled | up    | 2014-08-18T06:19:11.000000 | -               |\n| region@1       | nova-cells       | region@ubuntu       | internal | enabled  | up    | 2014-08-18T06:19:09.000000 | -               |\n| region@2       | nova-cert        | region@ubuntu       | internal | enabled  | down  | 2014-08-18T06:08:28.000000 | -               |\n| region@3       | nova-consoleauth | region@ubuntu       | internal | enabled  | up    | 2014-08-18T06:19:07.000000 | -               |\n+----------------+------------------+---------------------+----------+----------+-------+----------------------------+-----------------+\n\n$ nova --os-username admin service-enable 'region!child@ubuntu' nova-compute\nThe above command gives following error:\nERROR (ClientException): Unknown Error (HTTP 500)\n\n$ nova --os-username admin service-list\n+----------------+------------------+---------------------+----------+---------+-------+----------------------------+-----------------+\n| Id             | Binary           | Host                | Zone     | Status  | State | Updated_at                 | Disabled Reason |\n+----------------+------------------+---------------------+----------+---------+-------+----------------------------+-----------------+\n| region!child@1 | nova-conductor   | region!child@ubuntu | internal | enabled | up    | 2014-08-18T06:52:37.000000 | -               |\n| region!child@3 | nova-cells       | region!child@ubuntu | internal | enabled | up    | 2014-08-18T06:52:40.000000 | -               |\n| region!child@4 | nova-scheduler   | region!child@ubuntu | internal | enabled | up    | 2014-08-18T06:52:41.000000 | -               |\n| region!child@5 | nova-compute     | region!child@ubuntu | nova     | enabled | up    | 2014-08-18T06:52:42.000000 | -               |\n| region@1       | nova-cells       | region@ubuntu       | internal | enabled | up    | 2014-08-18T06:52:40.000000 | -               |\n| region@2       | nova-cert        | region@ubuntu       | internal | enabled | down  | 2014-08-18T06:08:28.000000 | -               |\n| region@3       | nova-consoleauth | region@ubuntu       | internal | enabled | up    | 2014-08-18T06:52:39.000000 | -               |\n+----------------+------------------+---------------------+----------+---------+-------+----------------------------+-----------------+\n\n\nThe nova-api log shows the following error, after we try to disable/enable the child cell service.\n\noutput of nova-api.log:\n\n2014-08-18 15:18:23.848 DEBUG nova.api.openstack.wsgi [req-c8e2b844-6aa4-4819-b4f4-38bfe30240f0 admin demo] Action: 'update', body: {\"binary\": \"nova-compute\", \"host\": \"region!child@ubuntu\"} from (pid=11556) _process_stack /opt/stack/nova/nova/api/openstack/wsgi.py:940\n2014-08-18 15:18:23.848 DEBUG nova.api.openstack.wsgi [req-c8e2b844-6aa4-4819-b4f4-38bfe30240f0 admin demo] Calling method '<bound method ServiceController.update of <nova.api.openstack.compute.contrib.services.ServiceController object at 0x7f16bd608510>>' (Content-type='application/json', Accept='application/json') from (pid=11556) _process_stack /opt/stack/nova/nova/api/openstack/wsgi.py:945\n2014-08-18 15:18:23.930 ERROR object [req-c8e2b844-6aa4-4819-b4f4-38bfe30240f0 admin demo] Error setting Service.id\n2014-08-18 15:18:23.930 TRACE object Traceback (most recent call last):\n2014-08-18 15:18:23.930 TRACE object   File \"/opt/stack/nova/nova/objects/base.py\", line 70, in setter\n2014-08-18 15:18:23.930 TRACE object     field.coerce(self, name, value))\n2014-08-18 15:18:23.930 TRACE object   File \"/opt/stack/nova/nova/objects/fields.py\", line 166, in coerce\n2014-08-18 15:18:23.930 TRACE object     return self._type.coerce(obj, attr, value)\n2014-08-18 15:18:23.930 TRACE object   File \"/opt/stack/nova/nova/objects/fields.py\", line 231, in coerce\n2014-08-18 15:18:23.930 TRACE object     return int(value)\n2014-08-18 15:18:23.930 TRACE object ValueError: invalid literal for int() with base 10: 'region!child@5'\n2014-08-18 15:18:23.930 TRACE object\n2014-08-18 15:18:23.934 ERROR nova.api.openstack [req-c8e2b844-6aa4-4819-b4f4-38bfe30240f0 admin demo] Caught error: invalid literal for int() with base 10: 'region!child@5'\n2014-08-18 15:18:23.934 TRACE nova.api.openstack Traceback (most recent call last):\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/api/openstack/__init__.py\", line 125, in __call__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return req.get_response(self.application)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/usr/lib/python2.7/dist-packages/webob/request.py\", line 1320, in send\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     application, catch_exc_info=False)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/usr/lib/python2.7/dist-packages/webob/request.py\", line 1284, in call_application\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     app_iter = application(self.environ, start_response)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 144, in __call__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return resp(environ, start_response)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/python-keystoneclient/keystoneclient/middleware/auth_token.py\", line 663, in __call__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return self.app(env, start_response)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 144, in __call__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return resp(environ, start_response)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 144, in __call__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return resp(environ, start_response)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/usr/local/lib/python2.7/dist-packages/routes/middleware.py\", line 131, in __call__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     response = self.app(environ, start_response)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 144, in __call__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return resp(environ, start_response)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 130, in __call__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     resp = self.call_func(req, *args, **self.kwargs)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/usr/lib/python2.7/dist-packages/webob/dec.py\", line 195, in call_func\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return self.func(req, *args, **kwargs)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/api/openstack/wsgi.py\", line 917, in __call__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     content_type, body, accept)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/api/openstack/wsgi.py\", line 983, in _process_stack\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     action_result = self.dispatch(meth, request, action_args)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/api/openstack/wsgi.py\", line 1070, in dispatch\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return method(req=request, **action_args)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/api/openstack/compute/contrib/services.py\", line 206, in update\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     self.host_api.service_update(context, host, binary, status_detail)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/compute/cells_api.py\", line 579, in service_update\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     db_service)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/objects/service.py\", line 67, in _from_db_object\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     service[key] = db_service[key]\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/objects/base.py\", line 398, in __setitem__\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     setattr(self, name, value)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/objects/base.py\", line 70, in setter\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     field.coerce(self, name, value))\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/objects/fields.py\", line 166, in coerce\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return self._type.coerce(obj, attr, value)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack   File \"/opt/stack/nova/nova/objects/fields.py\", line 231, in coerce\n2014-08-18 15:18:23.934 TRACE nova.api.openstack     return int(value)\n2014-08-18 15:18:23.934 TRACE nova.api.openstack ValueError: invalid literal for int() with base 10: 'region!child@5'", 
            "date_created": "2014-08-25 12:19:36.025388+00:00", 
            "author": "https://api.launchpad.net/1.0/~rajesh-tailor"
        }, 
        {
            "content": "Fix proposed to branch: master\nReview: https://review.openstack.org/118672", 
            "date_created": "2014-09-03 16:01:57.526193+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "There is a common problem with all service related methods in HostAPI.\nIn `service_get_all` (which corresponds to service-list), the ServiceProxy is used because we can't cast objects returned by cells to Service objects as ID's returned by cells contain full cell-path and it needs to be stripped out before creating Service objects. \n\nThe use of this proxy needs to be implemented in other functions as well - \nservice_get_by_compute_host - used by evacuate\nservice_update - used by service-enable and service-disable\n\nRajesh if you are no longer working on this, I have a patch ready for this which I can push.", 
            "date_created": "2014-10-06 12:48:14.460009+00:00", 
            "author": "https://api.launchpad.net/1.0/~dheeraj-gupta4"
        }, 
        {
            "content": "Fix proposed to branch: master\nReview: https://review.openstack.org/126498", 
            "date_created": "2014-10-07 09:31:07.753218+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Change abandoned by Rajesh Tailor (<email address hidden>) on branch: master\nReview: https://review.openstack.org/118672\nReason: Similar patch has submitted to address this issue.\nplease refer: https://review.openstack.org/#/c/126498", 
            "date_created": "2014-10-10 07:14:24.205130+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/126498\nCommitted: https://git.openstack.org/cgit/openstack/nova/commit/?id=fcd24c6774af0add2bf20c604232e4db9747da7d\nSubmitter: Jenkins\nBranch:    master\n\ncommit fcd24c6774af0add2bf20c604232e4db9747da7d\nAuthor: Dheeraj Gupta <email address hidden>\nDate:   Tue Oct 7 09:18:27 2014 +0000\n\n    Extends use of ServiceProxy to more methods in HostAPI in cells\n    \n    Cells prepend full cell path to the service ID before returning any\n    service related info. This means service ID is non numeric and can't\n    be cast into Service objects.  In cells, service_get_all method\n    in HostAPI (which is used to display list of services) strips out\n    the cell path from received IDs, creates Service objects using\n    remaining numerical ID and uses a ServiceProxy to associate cell paths\n    Service objects.\n    However, other service related methods do not do so. They include:\n     - service_update (Used for enabling/disabling services)\n     - service_get_all_by_host (Used for evacuation)\n    These functions try to cast received service info (with alphanumeric\n    service IDs) into Service objects and fail with a ValueError.\n    This leads to API cell throwing Error 500 for service-enable,\n    service-disable and evacuate.\n    This patch extends the ServiceProxy usage to both these methods. It\n    also changes the corresponding HostAPI tests.\n    \n    Change-Id: Iff2707602d5fabfbe8438150b5ad74b3c31bb011\n    Closes-Bug: 1361180\n", 
            "date_created": "2014-11-22 14:45:54.466362+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Fix proposed to branch: stable/icehouse\nReview: https://review.openstack.org/138308", 
            "date_created": "2014-12-02 10:23:41.963460+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Fix proposed to branch: stable/juno\nReview: https://review.openstack.org/138374", 
            "date_created": "2014-12-02 14:15:15.593667+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/138374\nCommitted: https://git.openstack.org/cgit/openstack/nova/commit/?id=2da234190346d76725017b4ee7570d0a7e89a91c\nSubmitter: Jenkins\nBranch:    stable/juno\n\ncommit 2da234190346d76725017b4ee7570d0a7e89a91c\nAuthor: Dheeraj Gupta <email address hidden>\nDate:   Tue Oct 7 09:18:27 2014 +0000\n\n    Extends use of ServiceProxy to more methods in HostAPI in cells\n    \n    Cells prepend full cell path to the service ID before returning any\n    service related info. This means service ID is non numeric and can't\n    be cast into Service objects.  In cells, service_get_all method\n    in HostAPI (which is used to display list of services) strips out\n    the cell path from received IDs, creates Service objects using\n    remaining numerical ID and uses a ServiceProxy to associate cell paths\n    Service objects.\n    However, other service related methods do not do so. They include:\n     - service_update (Used for enabling/disabling services)\n     - service_get_all_by_host (Used for evacuation)\n    These functions try to cast received service info (with alphanumeric\n    service IDs) into Service objects and fail with a ValueError.\n    This leads to API cell throwing Error 500 for service-enable,\n    service-disable and evacuate.\n    This patch extends the ServiceProxy usage to both these methods. It\n    also changes the corresponding HostAPI tests.\n    \n    Note: The required unit-tests are manually added to the below path,\n    as new path for unit-tests is not present in stable/juno release.\n    nova/tests/compute/test_host_api.py\n    \n    Conflicts:\n            nova/tests/unit/compute/test_host_api.py\n    \n    Change-Id: Iff2707602d5fabfbe8438150b5ad74b3c31bb011\n    Closes-Bug: 1361180\n    (cherry picked from commit fcd24c6774af0add2bf20c604232e4db9747da7d)\n", 
            "date_created": "2015-01-22 15:07:34.614602+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/138308\nCommitted: https://git.openstack.org/cgit/openstack/nova/commit/?id=c5411d22f0d1da0cb15f5d7c8511a4caec53b265\nSubmitter: Jenkins\nBranch:    stable/icehouse\n\ncommit c5411d22f0d1da0cb15f5d7c8511a4caec53b265\nAuthor: Dheeraj Gupta <email address hidden>\nDate:   Tue Oct 7 09:18:27 2014 +0000\n\n    Extends use of ServiceProxy to more methods in HostAPI in cells\n    \n    Cells prepend full cell path to the service ID before returning any\n    service related info. This means service ID is non numeric and can't\n    be cast into Service objects.  In cells, service_get_all method\n    in HostAPI (which is used to display list of services) strips out\n    the cell path from received IDs, creates Service objects using\n    remaining numerical ID and uses a ServiceProxy to associate cell paths\n    Service objects.\n    However, other service related methods do not do so. They include:\n     - service_update (Used for enabling/disabling services)\n     - service_get_all_by_host (Used for evacuation)\n    These functions try to cast received service info (with alphanumeric\n    service IDs) into Service objects and fail with a ValueError.\n    This leads to API cell throwing Error 500 for service-enable,\n    service-disable and evacuate.\n    This patch extends the ServiceProxy usage to both these methods. It\n    also changes the corresponding HostAPI tests.\n    \n    Note: The required unit-tests are manually added to the below path,\n    as new path for unit-tests is not present in stable/icehouse release.\n    nova/tests/compute/test_host_api.py\n    \n    Conflicts:\n            nova/compute/cells_api.py\n            nova/tests/unit/compute/test_host_api.py\n    \n    Closes-Bug: 1361180\n    Change-Id: Iff2707602d5fabfbe8438150b5ad74b3c31bb011\n    (cherry picked from commit fcd24c6774af0add2bf20c604232e4db9747da7d)\n", 
            "date_created": "2015-03-05 00:35:54.309022+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }
    ]
}