{
    "status": "Invalid", 
    "last_updated": "2015-04-01 12:33:04.166612+00:00", 
    "description": "I am facing an issue. If i send in 2 ports(created from 2 subnets) during provisioning then it fails but works with 1 port.\nIs this a bug or my paylaod is incorect. Since Rory faced issue with cli i am assuming my rest payload is ok\nThis is the rest paylaod.\n{ \"server\" : { \"name\" : \"loadbalancer-1-T55\" , \"imageRef\" : \"6b97a852-8eb1-498c-b9f0-d5374726a43c\" , \"flavorRef\" : \"1\" , \"key_name\" : \"demokey\" ,\n\"networks\" : [\n{ \"port\" : \"5dae5598-a5e6-4330-ba1c-5120d31c5f85\"} ,\n{ \"port\" : \"013d75e0-9cfe-4b32-9b6f-41c0a5063795\"}]\n}}\n", 
    "tags": [], 
    "importance": "Medium", 
    "heat": 10, 
    "link": "https://bugs.launchpad.net/nova/+bug/1168247", 
    "owner": "None", 
    "id": 1168247, 
    "index": 3350, 
    "created": "2013-04-12 06:05:03.752324+00:00", 
    "title": "Nova prvisioning fails when i attach 2 ports", 
    "comments": [
        {
            "content": "I am facing an issue. If i send in 2 ports(created from 2 subnets) during provisioning then it fails but works with 1 port.\nIs this a bug or my paylaod is incorect. Since Rory faced issue with cli i am assuming my rest payload is ok\nThis is the rest paylaod.\n{ \"server\" : { \"name\" : \"loadbalancer-1-T55\" , \"imageRef\" : \"6b97a852-8eb1-498c-b9f0-d5374726a43c\" , \"flavorRef\" : \"1\" , \"key_name\" : \"demokey\" ,\n\"networks\" : [\n{ \"port\" : \"5dae5598-a5e6-4330-ba1c-5120d31c5f85\"} ,\n{ \"port\" : \"013d75e0-9cfe-4b32-9b6f-41c0a5063795\"}]\n}}\n", 
            "date_created": "2013-04-12 06:05:03.752324+00:00", 
            "author": "https://api.launchpad.net/1.0/~ritesh-s-shetty"
        }, 
        {
            "content": "This is repeatable with cli also \n\nritesh@vcloudgrizzly:/opt/stack/logs/screen$ nova --debug boot --image d892d16d-fbbf-4e0e-9ee8-4c8a496833e7 --num-instances 2 --key-name riteshkeypair --flavor 1 riteshtest --nic port-id=599b64a9-9ad7-4720-ad22-3b16033f1a50 --nic port-id=f15122b9-40eb-44f0-b5e0-8eb0502072e6\n\nINFO (connectionpool:191) Starting new HTTP connection (1): 192.168.124.28\nDEBUG (connectionpool:283) \"POST http://192.168.124.28:8774/v2/02db3d5031e74cd9a78a11ee16844693/servers HTTP/1.1\" 500 128\nRESP: [500] {'date': 'Fri, 12 Apr 2013 23:51:28 GMT', 'content-length': '128', 'content-type': 'application/json; charset=UTF-8', 'x-compute-request-id': 'req-26ca1126-aae8-4bf3-8e6c-24d3c9e24177'}\nRESP BODY: {\"computeFault\": {\"message\": \"The server has either erred or is incapable of performing the requested operation.\", \"code\": 500}}\n\nDEBUG (shell:768) The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-26ca1126-aae8-4bf3-8e6c-24d3c9e24177)\nTraceback (most recent call last):\n  File \"/opt/stack/python-novaclient/novaclient/shell.py\", line 765, in main\n    OpenStackComputeShell().main(map(strutils.safe_decode, sys.argv[1:]))\n  File \"/opt/stack/python-novaclient/novaclient/shell.py\", line 701, in main\n    args.func(self.cs, args)\n  File \"/opt/stack/python-novaclient/novaclient/v1_1/shell.py\", line 282, in do_boot\n    server = cs.servers.create(*boot_args, **boot_kwargs)\n  File \"/opt/stack/python-novaclient/novaclient/v1_1/servers.py\", line 600, in create\n    **boot_kwargs)\n  File \"/opt/stack/python-novaclient/novaclient/v1_1/base.py\", line 163, in _boot\n    return_raw=return_raw, **kwargs)\n  File \"/opt/stack/python-novaclient/novaclient/base.py\", line 145, in _create\n    _resp, body = self.api.client.post(url, body=body)\n  File \"/opt/stack/python-novaclient/novaclient/client.py\", line 233, in post\n    return self._cs_request(url, 'POST', **kwargs)\n  File \"/opt/stack/python-novaclient/novaclient/client.py\", line 217, in _cs_request\n    **kwargs)\n  File \"/opt/stack/python-novaclient/novaclient/client.py\", line 199, in _time_request\n    resp, body = self.request(url, method, **kwargs)\n  File \"/opt/stack/python-novaclient/novaclient/client.py\", line 193, in request\n    raise exceptions.from_response(resp, body, url, method)\nClientException: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-26ca1126-aae8-4bf3-8e6c-24d3c9e24177)\nERROR: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-26ca1126-aae8-4bf3-8e6c-24d3c9e24177)\n\n\n", 
            "date_created": "2013-04-12 23:54:01.485784+00:00", 
            "author": "https://api.launchpad.net/1.0/~ritesh-s-shetty"
        }, 
        {
            "content": "I Noticed on Horizon iam able to attach mutiple nics. But actually what it is doing is sending mutiple network id's which works \n\n\nThis works since i am sending mutiple network id's\n\nritesh@vcloudgrizzly:/opt/stack/logs/screen$ nova --debug boot --image d892d16d-fbbf-4e0e-9ee8-4c8a496833e7 --num-instances 2 --key-name riteshkeypair --flavor 1 riteshtest --nic net-id=599b64a9-9ad7-4720-ad22-3b16033f1a50 --nic net-id=f15122b9-40eb-44f0-b5e0-8eb0502072e6\n", 
            "date_created": "2013-04-12 23:56:16.536649+00:00", 
            "author": "https://api.launchpad.net/1.0/~ritesh-s-shetty"
        }, 
        {
            "content": "Did some more testing looks like it accepts mutiple ports if they were created from 2 subnets belonging to 2 different networks. \r\nBut if i specify ports that were created from 2 subnets from in the same network then it doesnt work.", 
            "date_created": "2013-04-23 21:07:59.950850+00:00", 
            "author": "https://api.launchpad.net/1.0/~ritesh-s-shetty"
        }, 
        {
            "content": "I believe this might be the intended behavor. Why do you want two ports attached to a vm in the same subnet? A tenant could loop the network by bridging these interfaces which is probably why this isn't allowed. ", 
            "date_created": "2013-05-01 00:00:18.254352+00:00", 
            "author": "https://api.launchpad.net/1.0/~arosen"
        }, 
        {
            "content": "no thats not what i want. if you see my posts i am saying these 2 ports are on 2 different subnets but these 2 subnets belong to same network. I think it should work ", 
            "date_created": "2013-05-01 00:13:37.312743+00:00", 
            "author": "https://api.launchpad.net/1.0/~ritesh-s-shetty"
        }, 
        {
            "content": "I don't think that assigning two subnets is any safer than two ports on the same network if the instance still has the ability to provide a L2 loop.\r\n\r\nThat said, I don't think that the 500 error is the right response from nova in this case. Can you track down the server-side logs for this (probably nova-compute.log)?", 
            "date_created": "2013-05-08 16:42:46.656115+00:00", 
            "author": "https://api.launchpad.net/1.0/~danms"
        }, 
        {
            "content": "Segmentation is achieved using subnets whether the ports come from same network or different shouldnt matter in my opinion.  Quantum brings in this very powerfull feature to do segmentation using subnet but if nova cant support it and wants us to create new networks then it is not good.", 
            "date_created": "2013-05-08 16:51:50.110134+00:00", 
            "author": "https://api.launchpad.net/1.0/~ritesh-s-shetty"
        }, 
        {
            "content": "also i think i have a works around(need to test it though)\ni am planning to create port with 2 subnets which come out of same network. Then attach this port while provisioning. \n\nIf this works is this different from attaching 2 ports while provisioning ?", 
            "date_created": "2013-05-08 16:54:45.047051+00:00", 
            "author": "https://api.launchpad.net/1.0/~ritesh-s-shetty"
        }, 
        {
            "content": "2 year old bug that didn't include follow up, closing", 
            "date_created": "2015-04-01 12:32:56.572482+00:00", 
            "author": "https://api.launchpad.net/1.0/~sdague"
        }
    ]
}