{
    "status": "Fix Released", 
    "last_updated": "2013-10-17 11:36:33.382869+00:00", 
    "description": "We've identified that when an instance build fails because it has exceeded the number of retries (i.e. been tried on 3 different hosts) the upstream logic in the scheduler does not correctly set the VM state to ERROR.\n\nThere is an exception handler for NoValidHost in manager.run_instance(), but it relies on request_spec[instance_uuids] to determine which instances to put into the Error State, and schedule_run_instance removes this value (as its normally about to split the request up into several separate requests).", 
    "tags": [], 
    "importance": "High", 
    "heat": 20, 
    "link": "https://bugs.launchpad.net/nova/+bug/1182056", 
    "owner": "https://api.launchpad.net/1.0/~moorryan", 
    "id": 1182056, 
    "index": 1100, 
    "created": "2013-05-20 13:09:54.363655+00:00", 
    "title": "Failed VM's not set to error state on exception", 
    "comments": [
        {
            "content": "We've identified that when an instance build fails because it has exceeded the number of retries (i.e. been tried on 3 different hosts) the upstream logic in the scheduler does not correctly set the VM state to ERROR.\n\nThere is an exception handler for NoValidHost in manager.run_instance(), but it relies on request_spec[instance_uuids] to determine which instances to put into the Error State, and schedule_run_instance removes this value (as its normally about to split the request up into several separate requests).", 
            "date_created": "2013-05-20 13:09:54.363655+00:00", 
            "author": "https://api.launchpad.net/1.0/~moorryan"
        }, 
        {
            "content": "Fix proposed to branch: master\nReview: https://review.openstack.org/29780", 
            "date_created": "2013-05-20 14:20:46.861674+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/29780\nCommitted: http://github.com/openstack/nova/commit/aefc28dd481354edd0f3b5aec18db006680b2ffe\nSubmitter: Jenkins\nBranch:    master\n\ncommit aefc28dd481354edd0f3b5aec18db006680b2ffe\nAuthor: Ryan Moore <email address hidden>\nDate:   Mon May 20 14:56:55 2013 +0100\n\n    set ERROR state when scheduler hits max attempts\n    \n    Presently when scheduler raises NoValidHost due to max attempts\n    being reached, the instance remains in a build state.\n    Exception handler for NoValidHost in manager.run_instance() needs\n    request_spec[instance_uuids] to know which host to put into an\n    error state in _set_vm_state_and_notify().\n    schedule_run_instances() was popping instance_uuids from the\n    request_spec prior to a call to _schedule().\n    Changed pop of instance_uuids prior to call to _schedule() to be a get.\n    Added pop of instance_uuids to beneath call to _schedule() as\n    individual creates do not need them.\n    \n    Change-Id: I9654820e01d5611763e9e673f15f46b947d09e6d\n    Fixes: bug #1182056\n", 
            "date_created": "2013-05-22 13:26:47.343452+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Fix proposed to branch: stable/grizzly\nReview: https://review.openstack.org/30892", 
            "date_created": "2013-05-29 14:35:05.252338+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/30892\nCommitted: http://github.com/openstack/nova/commit/7726dae1c3720477191cfdb239fdd2c5d0952285\nSubmitter: Jenkins\nBranch:    stable/grizzly\n\ncommit 7726dae1c3720477191cfdb239fdd2c5d0952285\nAuthor: Ryan Moore <email address hidden>\nDate:   Mon May 20 14:56:55 2013 +0100\n\n    set ERROR state when scheduler hits max attempts\n    \n    Presently when scheduler raises NoValidHost due to max attempts\n    being reached, the instance remains in a build state.\n    Exception handler for NoValidHost in manager.run_instance() needs\n    request_spec[instance_uuids] to know which host to put into an\n    error state in _set_vm_state_and_notify().\n    schedule_run_instances() was popping instance_uuids from the\n    request_spec prior to a call to _schedule().\n    Changed pop of instance_uuids prior to call to _schedule() to be a get.\n    Added pop of instance_uuids to beneath call to _schedule() as\n    individual creates do not need them.\n    \n    Conflicts:\n    \tnova/scheduler/filter_scheduler.py\n    \n    Change-Id: I9654820e01d5611763e9e673f15f46b947d09e6d\n    Fixes: bug #1182056\n    (cherry picked from commit aefc28dd481354edd0f3b5aec18db006680b2ffe)\n", 
            "date_created": "2013-06-18 20:18:53.538845+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }
    ]
}